FROM ${IMAGE_FROM}

MAINTAINER ${IMAGE_MAINTAINER}

ENV \
    APP_HOSTNAME="test.planet4.dev" \
    COMPOSER="composer.json" \
    GIT_REF="${GIT_REF}" \
    WP_EXTRA_CONFIG="\$redis_server=array('host' => 'redis','port' => 6379,'database' => 0);" \
    WP_TITLE="Greenpeace International - Staging Site"

COPY . /app/
