# Greenpeace Planet 4 Application Base
# Branch: dev-feature/gitrepositories
# Commit: c21d3483036c1ddf85b5d9693eb42adeebc1217c
# Build:  (local)
# ------------------------------------------------------------------------
#                     DO NOT MAKE CHANGES HERE
# This file is built automatically from ./templates/Dockerfile.in
# ------------------------------------------------------------------------

FROM gcr.io/planet-4-151612/p4-onbuild:0.3.1

MAINTAINER Raymond Walker <raymond.walker@greenpeace.org>

ENV APP_HOSTNAME "test.planet4.dev"
ENV COMPOSER="composer-dev.json"
ENV GIT_REF="dev-feature/gitrepositories"
ENV SSL_ENABLED "false"
ENV WP_TITLE="Greenpeace International - Development Site"
