FROM gcr.io/planet-4-151612/p4-onbuild

MAINTAINER Raymond Walker <raymond.walker@greenpeace.org>

ENV WP_TITLE="Greenpeace International"
ENV APP_HOSTNAME "p4.greenpeace.org"
ENV SSL_ENABLED "false"
