FROM ${IMAGE_FROM}

MAINTAINER ${IMAGE_MAINTAINER}

ENV APP_HOSTNAME "test.planet4.dev"
ENV COMPOSER="composer-dev.json"
ENV GIT_REF="${GIT_REF}"
ENV SSL_ENABLED "false"
ENV WP_TITLE="Greenpeace International - Development Site"
ENV WP_CLI_CONFIG_PATH="/app/source/wp-config.yml"
ENV WP_CLI_CACHE_DIR="/app/.wp-cli/cache"
ENV WP_CLI_DISABLE_AUTO_CHECK_UPDATE="true"

COPY . /app/
