FROM ${IMAGE_FROM}

MAINTAINER ${IMAGE_MAINTAINER}

ENV \
    APP_HOSTNAME="test.planet4.dev" \
    COMPOSER="composer-dev.json" \
    GIT_REF="${GIT_REF}" \
    SSL_ENABLED="false" \
    WP_SITE_PROTOCOL="http" \
    WP_CLI_CACHE_DIR="/app/.wp-cli/cache" \
    WP_CLI_CONFIG_PATH="/app/source/wp-config.yml" \
    WP_CLI_DISABLE_AUTO_CHECK_UPDATE="true" \
    WP_EXTRA_CONFIG="\$redis_server=array('host' => 'redis','port' => 6379,'auth' => '12345','database' => 0);" \
    WP_TITLE="Greenpeace International - Development Site"

COPY . /app/
